baseurl = "/"
title = "Link to Bin"
languageCode = "en-us"
disqusShortname = "spf13"
theme = "spf13"
copyright = ""
MetaDataFormat = "toml"
googleAnalytics = ""

[author]
    name = "Bin YE"

[indexes]
    tag = "tags"
    topic = "topics"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true